source 'https://rubygems.org'

# ruby '2.1.2'
gem 'rails', '4.0.1'
gem 'cancan'
gem 'pg'
gem 'mysql2'
gem 'chronic'
gem "nested_form"
gem "highcharts-rails", "~> 3.0.0"
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'carrierwave'
gem 'fog'
gem 'rmagick'
gem 'country_select'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-modal-rails'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'twitter-bootstrap-rails'
gem 'jquery-datatables-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'sdoc', require: false
gem 'devise'
gem 'paperclip'
gem "ckeditor"
gem 'friendly_id'
gem 'execjs'
gem 'therubyracer'
gem 'delayed_job_active_record'
