# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

# # Examples:

# #   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
# #   Mayor.create(name: 'Emanuel', city: cities.first)

# user = User.new(first_name: 'admin',last_name: 'admin',email: 'admin@xemasupport.com',password: 'password',role: 'admin',confirmed_at: '2014-04-10 10:19:33.008972')
# user.save(:validate=>false)

# NatureOfReview.delete_all

# [ "Bad attitude",
#   "Billing/Accounts",
#   "Booking query",
# 	"Breach of contract",
# 	"Call centre",
# 	"Damaged goods",
# 	"Expiry date",
# 	"Feedback/response",
# 	"Hygiene",
# 	"Late/no delivery",
# 	"Out of stock",
# 	"Pricing/bar codes",
# 	"Repairs/servicing",
# 	"Spam",
# 	"Other"].each do |complaint|
# 			NatureOfReview.create(:title=>complaint,:review_type=>"complaint")
# 	end

# [
# 	"Billing/accounts",
# 	"Booking",
# 	"Call centre efficiency",
# 	"Contract",
# 	"Delivery on time",
# 	"Feedback",
# 	"Going the extra mile",
# 	"Great attitude",
# 	"Pricing",
# 	"Refund",
# 	"Repairs",
# 	"Stock",
# 	"Other"
# 	].each do |compliment|
# 			NatureOfReview.create(:title=>compliment,:review_type=>"compliment")
# 	end

#   Industry.delete_all

# 	["Air Travel",
#     "Banking",
# 	"Broadcast",
# 	"Bus Companies",
# 	"County Head Offices",
# 	"Doctors",
# 	"Entertainment",
# 	"Government",
# 	"Hospitals",
# 	"Hotels",
# 	"Insurance",
# 	"Internet",
# 	"Motor",
# 	"Opticians",
# 	"Pay TV",
# 	"Police",
# 	"Real Estate",
# 	"Restaurants",
# 	"Retail",
# 	"Schools",
# 	"Supermarkets",
# 	"Taxi Companies",
# 	"Telecommunications",
# 	"University"].each do |industry|
# 			Industry.create(:title=>industry)
# 	end

# 	Company.delete_all
    
	
# 	[ "ABC Bank",
# 	"Bank of  Africa Kenya Limited",
# 	"Bank of Baroda",
# 	"Bank Of India",
# 	"Barclays",
# 	"CFC Stanbic",
# 	"Chase Bank",
# 	"Citi Bank",
# 	"CBA",
# 	"Consolidated Bank",
# 	"Co-operative Bank Of Kenya",
# 	"Credit Bank",
# 	"Diamond Trust Bank",
# 	"Eco Bank",
# 	"Equatorial Commercial Bank Limited",
# 	"Equity Bank",
# 	"Family Bank",
# 	"Fidelity Bank",
# 	"Fina Bank",
# 	"First Community Bank",
# 	"Giro Bank",
# 	"Guardian Bank",
# 	"Gulf Africa Bank",
# 	"Habib Bank AG Zurich",
# 	"I&M",
# 	"Imperial Bank",
# 	"Jamii Bora Bank",
# 	"Kenya Commercial Bank",
# 	"K-rep Bank",
# 	"Middle East Bank of Kenya",
# 	"National Bank of Kenya",
# 	"NIC Bank",
# 	"Oriental Commercial Bank",
# 	"Paramount Bank",
# 	"Prime Bank",
# 	"Standard Chartered Bank",
# 	"Trans National Bank",
# 	"Victoria Commercial Bank"].each do |company|
		

# 	  @banking = Industry.find_by_title("Banking")
# 	  bank_id = @banking.id    	
# 		Company.create(:title=>company,:industry_id=> bank_id)
# 	  end

	

# 	[ "AAR",
# 	"APA",
# 	"Amaco",
# 	"Apollo",
# 	"Britam",
# 	"Cannon",
# 	"Capex",
# 	"CFC",
# 	"CIC",
# 	"Continental" ,
# 	"Corporate",
# 	"Directline",
# 	"ICEA-LION",
# 	"Fidelity Shield",
# 	"First Assurance",
# 	"GA",
# 	"Gateway",
# 	"Geminia",
# 	"Heritage",
# 	"Intra Africa",
# 	"Invesco",
# 	"Jubilee",
# 	"Kenindia",
# 	"Kenya Orient",
# 	"Madison",
# 	"Mayfair",
# 	"Mercatile",
# 	"Metropolitan Life",
# 	"Monarch",
# 	"Occidental",
# 	"Old Mutual",
# 	"Pacis",
# 	"Pan Africa Life",
# 	"Phoenix",
# 	"Pioneer Assurance",
# 	"Real",
# 	"Resolution",
# 	"Shield Assurance",
# 	"Takaful",
# 	"Tausi",
# 	"Trident",
# 	"UAP",
# 	"Xplico"].each do |company|

# 		@insurance = Industry.find_by_title("Insurance")
# 	    insurance_id = @insurance.id

# 		Company.create(:title=>company,:industry_id=> insurance_id)
# 	end




# 	[ "Airtel",
# 	"Orange",
# 	"Yu"].each do |company|

# 		@tellecommunication = Industry.find_by_title("Telecommunications")
# 	    tellecommunication_id = @tellecommunication.id

# 		Company.create(:title=>company,:industry_id=> tellecommunication_id)
# 	end



# 	[ "Nakumatt",
# 	"Uchumi",
# 	"Naivas",
# 	"Tuskys",
# 	"Chandarana",
# 	"Ukwala"].each do |company|

# 		@supermarkets = Industry.find_by_title("Supermarkets")
# 	    supermarkets_id = @supermarkets.id

# 		Company.create(:title=>company,:industry_id=> supermarkets_id)
# 	end



# [ "Best Western Premier",
# 	"Boma",
# 	"Collingham Gardens",
# 	"Country Lodge",
# 	"Country Lodg",
# 	"Crowne Plaza",
# 	"Eastland", 
# 	"Eka", 
# 	"Emerald Hotel",
# 	"Fahari", 
# 	"Fairmont Norfolk",
# 	"Fairview", 
# 	"Hemingways", 
# 	"Hemingways",
# 	"Hilton Hotel",
# 	"Hotel Embassy",
# 	"Hotel LaMada",
# 	"House of Waine",
# 	"InterContinental Nairobi",
# 	"Jacaranda Hotel",
# 	"Jupiter Guest Resort Langata",
# 	"Kenya Comfort Hotel",
# 	"Laico Regency",
# 	"Maasai Ostrich Resort",
# 	"Meltonia Luxury",
# 	"Nairobi Safari Club",
# 	"Nairobi Transit Hotel",
# 	"Nomad Palace Hotel",
# 	"Ole Sereni",
# 	"Palacina Residence & Suites",
# 	"Panari Hotel",
# 	"Park Place Hotel",
# 	"Parklands Shade Hotel",
# 	"Pride Inn Hotel",
# 	"Progressive Park Hotel",
# 	"Reata Serviced Apartments",
# 	"Red Court Hotel",
# 	"Safari Park",
# 	"Sankara",
# 	"Sarova Panafric",
# 	"Sarova Stanley",
# 	"Serena",
# 	"Silver Springs Hotel",
# 	"Southern Sun Mayfair",
# 	"Sovereign Suites",
# 	"Summerdale Inn",
# 	"Sunstar Hotel",
# 	"The Heron Portico",
# 	"The Ndemi Place",
# 	"Tribe Hotel",
# 	"Villa Rosa Kempinski",
# 	"Windsor",
# 	"Kipepeo",
# 	"680 Hotel",
# 	"Central Park Hotel",
# 	"Olive Gardens Hotel",
# 	"Nanchang Hotel",
# 	"Blue Posts Hotel",
# 	"LAICO Regency Hotel",
# 	"Sentrim  Boulevard",
# 	"Grand Royal Hotel",
# 	"Utalii Hotel",
# 	"Jamiat Hotel",
# 	"Oakwood Hotel",
# 	"Marble Arch Hotel",
# 	"Oryx Hotel",
# 	"Sportsview Hotel",
# 	"Parkside Hotel",
# 	"Hennessis Hotel",
# 	"Hotel Greton",
# 	"West Breeze Hotel",
# 	"Kivi  Hotel",
# 	"Eastland Hotel",
# 	"Nairobi Upper Hill Hotel",
# 	"Clarence House Nairobi",
# 	"New Hillcrest Hotel",
# 	"Arkland Palace Hotel",
# 	"Blue Hut Hotel",
# 	"Lenana Mount Hotel",
# 	"The Headquarters Inn",
# 	"Hotel Ambassadeur",
# 	"The Strand Hotel",
# 	"67 Airport Hotel",
# 	"Dafam Hotel",
# 	"Karibu Hotel",
# 	"Laibon Hotel",
# 	"Radisson Blu Hotel",
# 	"Babobab Holiday",
# 	"Bamburi Beach Hotel",
# 	"Diani Beach Reef Resort",
# 	"Forty Thieves Beach",
# 	"Indiana Beach Hotel",
# 	"Jacaranda Beach Resort",
# 	"Kahama Hotel",
# 	"Kenya Bay Beach Hotel",
# 	"Leisure Lodge Beach",
# 	"Leopard Beach Resort",
# 	"Mombasa Beach Hotel",
# 	"Serena Beach Hotel",
# 	"Nomads Beach Restaurant",
# 	"Northcoast Beach hotel",
# 	"Nyali Golf Club",
# 	"Nyali Beach Hotel",
# 	"Pinewood Beach Resort",
# 	"Sarova Whitesands",
# 	"Severin Sea Lodge",
# 	"Swahili Beach Resort",
# 	"Travellers Beach Hotel",
# 	"Kiboko Bay",
# 	"Imperial",
# 	"Hotel DewChurch Drive",
# 	"Hotel Marina",
# 	"Parkview Safari",
# 	"Whirlspring",
# 	"New Victoria",
# 	"Hotel Palmers",
# 	"Kisumu Guest",
# 	"Kisumu Beach"].each do |company|

# 		@hotels = Industry.find_by_title("Hotels")
# 	    hotels_id = @hotels.id

# 		Company.create(:title=>company,:industry_id=> hotels_id)
# 	end





# [ "African Express Airways",
# 	"Air Arabia ",
# 	"Air France",
# 	"Air Kenya Express",
# 	"Astral Aviation",
# 	"Blue Bird Aviation",
# 	"Comic Aviation",
# 	"Delta Connection",
# 	"East African Safari Air",
# 	"Emirates",
# 	"Ethiopia",
# 	"Etihad Airways",
# 	"Fly540",
# 	"KLM",
# 	"Kenya Airways",
# 	"Mombasa Air Safari",
# 	"Precision Airways",
# 	"Rwanda Air",
# 	"Safarilink Aviation",
# 	"South African Airways",
# 	"Swiss Airlines",
# 	"Turkish Airline",
# 	"Yemenia",
# 	"Virgin Atlantic Cargo "].each do |company|

# 		@air_travel = Industry.find_by_title("Air Travel")
# 	    airtravel_id = @air_travel.id

# 		Company.create(:title=>company,:industry_id=> airtravel_id)
# 	end



#   [ "Zuku",
# 	"Kenya Data Networks",
# 	"Access Kenya ",
# 	"Telkom Kenya",
# 	"Safaricom",
# 	"Iway Africa",
# 	"Jamii Telecom",
# 	"Swift Global",
# 	"Mobile Telephony",
# 	"Call Key Networks"].each do |company|

# 		@internet = Industry.find_by_title("Internet")
# 	    internet_id = @internet.id

# 		Company.create(:title=>company,:industry_id=> internet_id)
# 	end


# 	[ "Citizen TV",
# 	"KTN",
# 	"K24",
# 	"NTV",
# 	"KBC",
# 	"Kiss TV",
# 	"Family TV",
# 	"GBS TV",
# 	"QTV",
# 	"UTV",
# 	"Sayare TV",
# 	"Baraka / Feba FM",
# 	"Biblia Husema",
# 	"BBC",
# 	"Capital FM",
# 	"Citizen Radio ",
# 	"Community Eye",
# 	"Easy FM",
# 	"Econews Africa",
# 	"Family Radio",
# 	"Frontier FM",
# 	"Ghetto Radio",
# 	"Head of Metro FM",
# 	"Homeboyz Radio",
# 	"Hope FM",
# 	"Iqra FM",
# 	"Jesus is Lord FM",
# 	"Kameme FM",
# 	"Kass FM",
# 	"KBC Radio",
# 	"Kiss FM",
# 	"Magic Radio Ltd",
# 	"Mbaitu FM",
# 	"Metro FM",
# 	"Milele FM",
# 	"News Editor",
# 	"News Service",
# 	"Pwani FM",
# 	"Radio Mambo",
# 	"Radio Rahma",
# 	"Radio Salaam",
# 	"Radio Simba",
# 	"Radio Umoja",
# 	"Radio Waumini",
# 	"Sauti ya Mwananchi FM",
# 	"Sayare Radio",
# 	"Shake FM",
# 	"Star FM",
# 	"Syokimau FM",
# 	"Transworld Radio",
# 	"Voice of America",
# 	"West FM"].each do |company|

# 		@broadcast = Industry.find_by_title("Broadcast")
# 	    broadcast_id = @broadcast.id

# 		Company.create(:title=>company,:industry_id=> broadcast_id)
# 	end

#create university list
# ["Adventist University of Africa",
# "Africa International",
# "Africa Nazarene",
# "Catholic University",
# "Daystar",
# "Inoorero University",
# "JKUAT",
# "KCA University",
# "Kenyatta University",
# "Kiriri Women's University",
# "Management University",
# "Multimedia University",
# "Pan Africa Christian",
# "Strathmore",
# "Technical University",
# "The East African University",
# "USIU",
# "University of Nairobi"
# ].each do |company|
# 	institution = Industry.find_by_title("University")
# 	Company.create(:title=>company,:industry_id=> institution.id )
# end


#    [ "Zuku Tv",
# 	"Go TV",
# 	"Star Times",
# 	"Multichoice"].each do |company|

# 		@pay_tv = Industry.find_by_title("Pay TV")
# 	    paytv_id = @pay_tv.id

# 		Company.create(:title=>company,:industry_id=> paytv_id)
# 	end





# 	[ "1001 Nights Restaurant",
# 	"360 Degrees Pizza",
# 	"7 Degrees Bar & Restaurant",
# 	"88 Restaurant",
# 	"About thyme",
# 	"Absolute Juice Bar",
# 	"Abyssinia",
# 	"Aero club",
# 	"Afma Gardenss",
# 	"African Fiesta",
# 	"Afya Gardens Bar",
# 	"Agenda",
# 	"Ai Saracini",
# 	"Aksum bar",
# 	"Akuche Migingo",
# 	"Al Pasha Lounge",
# 	"Alabastar lounge",
# 	"Aladdin Restaurant",
# 	"Alan Bobbes Bistro",
# 	"Alexandre",
# 	"Alfajiri Bar & Restaurant",
# 	"Alyas Restaurant",
# 	"AL-YUSRA Restaurant",
# 	"Amaica ",
# 	"Ambiance",
# 	"Amboseli Gardenss",
# 	"Anghiti  ",
# 	"Aquarious Grill",
# 	"Arlecchino",
# 	"Artcaffe",
# 	"Artisan",
# 	"Asmara Lounge",
# 	"Atrium",
# 	"Avalon Tavern",
# 	"Avanti Restaurant",
# 	"Azalea-caribea",
# 	"Babalu's Bar",
# 	"Bagicha",
# 	"Bahari Bistro",
# 	"Bamboo",
# 	"Bangkok ",
# 	"Bar. B.Q Tonight",
# 	"Baraza ",
# 	"Barrels Pub",
# 	"Bashasha",
# 	"Basil's",
# 	"Beehive Bar & Restaurant",
# 	"Beirut Lebanese",
# 	"Bela Madunina",
# 	"Belcanto Caterers",
# 	"Bella Afrique",
# 	"Benares",
# 	"Berbey Oasis",
# 	"Bhandini",
# 	"Big Five Restaurant",
# 	"Big Square Kenya",
# 	"Black Diamond",
# 	"Black Gold Café",
# 	"Blackbox Lounge",
# 	"Blackforest House",
# 	"Blue Korner",
# 	"Blue Nile",
# 	"Blue Times and Toona Place",
# 	"Bobos Food Delight",
# 	"Bombay Chowpaty",
# 	"Bombay Restaurant",
# 	"Bonds Gardens Restaurant",
# 	"Bonkas Foods",
# 	"Brasserie",
# 	"Brew Bistro ",
# 	"Bridges Organic",
# 	"Burger Hut",
# 	"Burgerland",
# 	"Bustani Grill and Lounge",
# 	"Caboose",
# 	"Caesar's Palace",
# 	"Cafe American",
# 	"Cafe Brazil",
# 	"Café Brasserie",
# 	"Cafe Habibi & Sheesha Lounge",
# 	"Cafe Iliki Lunch Club",
# 	"Café Kigwa",
# 	"Cafe Latino",
# 	"Café Maghreb",
# 	"Cafe Tasse",
# 	"Café Villa Rosa",
# 	"Caffe Cream Bar & Restaurant",
# 	"Cake City",
# 	"Cake Hut",
# 	"Calabash Restaurant",
# 	"Calypso",
# 	"Can-Afrika Cafe",
# 	"Caprice",
# 	"Captain Grill",
# 	"Carnivore",
# 	"Casablanca",
# 	"Cedars",
# 	"Cefrose",
# 	"Cellar",
# 	"Champagne Bar",
# 	"Chancery Restaurant",
# 	"Changes Pub & Restaurant",
# 	"Checkers Inn",
# 	"Cheers Grill",
# 	"Chez L'ami",
# 	"Chez Loulou",
# 	"Chic Joint",
# 	"Chicago Pizza",
# 	"Chicken Inn",
# 	"China Anhui",
# 	"China City",
# 	"China Dragon",
# 	"China King",
# 	"Chinese Corner",
# 	"Chinese Kitchen",
# 	"Chiromo Pub & Restaurant",
# 	"Chocho Coffee Bar",
# 	"Chocho Restaurant",
# 	"Choice Pub & Restaurant",
# 	"Chopstix ",
# 	"Chowpaty Restaurant",
# 	"Cidi's Grill",
# 	"Cin Cin",
# 	"Circles Coffee Lounge & Bar",
# 	"CitiZone Caterers",
# 	"City Star",
# 	"Cloud Nine", 
# 	"Club 100",
# 	"Club House Bar",
# 	"Club Kutwa",
# 	"Club Legend",
# 	"Coco J",
# 	"Colosseum",
# 	"Conservatory Restaurant",
# 	"Cool Breeze Cafe",
# 	"Cool Breeze Gardenss",
# 	"Corner Affair Bistro",
# 	"Cravery Ltd",
# 	"Creamy Inn",
# 	"Crescent Bar & Restaurant",
# 	"Cupcakes by Chus",
# 	"Daas Ethiopia Restaurant",
# 	"Dalyn",
# 	"Damera Restaurant & Club",
# 	"Dancing Spoon",
# 	"Darbar-E-Tandoor",
# 	"Dari Restaurant",
# 	"Dass Restaurant",
#     "ebonairs", 
#     "Deep South",
# 	"Delicious",
# 	"Demesi Cafeteria",
# 	"Dial a Chef (The Green Apple)",
# 	"Divino",
# 	"Dominion Cafe",
# 	"Dorman’s air Kenya",
# 	"Double Dragon",
# 	"Dragon Pearl",
# 	"Eagles ",
# 	"Eastern Cuisine",
# 	"Eastern Delight Gardens",
# 	"Eastern Gardens Chinese Restaurant",
# 	"Eateries Restaurant",
# 	"Eden Bar & Restaurant",
# 	"Edens Pot Restaurant",
# 	"Eighteen Restaurant",
# 	"Emerald Gardens Thai",
# 	"Emmanuel's Cafe",
# 	"E-pizza & Fried Chicken",
# 	"Eunny Cafe",
# 	"Eva's Cafe",
# 	"Excellent and Taste Ltd",
# 	"Exchange Bar",
# 	"F K Restaurant",
# 	"Fang Fang",
# 	"Farmhouse",
# 	"Felix Pub & Restaurant",
# 	"Fiery Peach Pub & Restaurant",
# 	"Fiesta",
# 	"First Thing Restaurant",
# 	"Five Star",
# 	"Flame Flavours",
# 	"Flame Tree",
# 	"Flames Restaurant",
# 	"Flavours of Africa",
# 	"Fogo Gaucho",
# 	"Food For You",
# 	"Food Solace",
# 	"Four Café Bistro",
# 	"Four Corners Cafe",
# 	"Frankies Sports Bar & Lounge",
# 	"Fresh Attack",
# 	"Friends Club & Diner",
# 	"Furusato Japanese",
# 	"G Pot",
# 	"Galitos",
#     "Gallery at Samara",
# 	"Gatoyo Bar & Restaurant",
# 	"German Point",
# 	"Gipsy Bar",
# 	"Golden Grills",
# 	"Golden Spurs",
# 	"Golden Wings",
# 	"Gracefull Chinese",
# 	"Graybells Foodplace",
# 	"Growers Cafe Ltd",
# 	"Gugz Restaurant",
# 	"Haandi",
# 	"Habesha",
# 	"Half Past One Cafe",
# 	"Happiness And Love Restaurant",
# 	"Haru Japanese",
# 	"Havana",
# 	"Havana Coffee",
# 	"Haveli",
# 	"Healthy Food",
# 	"Hebakai",
# 	"Hemingways Brasserie",
# 	"Hidden Agenda Pub",
# 	"Highlands Cafe & Restaurant",
# 	"Home Pub",
# 	"Hongs Restaurant",
# 	"Hope Africa",
# 	"Hope Cafe",
# 	"Horseman",
# 	"Hot Dishes",
# 	"Hot n Corny",
# 	"Hotspot Club & Restaurant",
# 	"Humming BiRoad",
# 	"Impala Hotel",
# 	"Inka",
# 	"Ismailia Restaurant",
# 	"Jaddah Enterprises",
# 	"Jade Coffee House",
# 	"Jaganath Express",
# 	"Jambo Foods & Confectionery Ltd",
# 	"Jambo Grill",
# 	"Jamret Restaurants",
# 	"Jans Kitchen",
# 	"Japa Classic Cafe",
# 	"Java House",
# 	"Jazz Bar",
# 	"Jiko",
# 	"Jockey Pub",
# 	"Juice It Up",
# 	"Jumbi Silent Bar & Restaurant",
# 	"Jupiter Guest Resort",
# 	"K lounge",
# 	"Kadai King",
# 	"Kamanga Bar & Restaurant",
# 	"Karen Country Lounge",
# 	"Katanazi Restaurant",
# 	"Kates Bakers",
# 	"Kavs Fruit & Juice",
# 	"Kebab Korner",
# 	"Ken Cafe",
# 	"Kenchic Inn",
# 	"Kendu",
# 	"Kengeles",
# 	"Kengeria Restaurant",
# 	"Kenpride Foods ltd",
# 	"Kentmere Club",
# 	"Keynan's & Kimmi's",
# 	"KFC",
# 	"Khazana",
# 	"Kingfisher Bar",
# 	"Kings",
# 	"Kipepeo",
# 	"Kivuli Grill",
# 	"Klique",
# 	"Kowloon Gardens Chinese",
# 	"KTDA Tea House",
# 	"Kula Korna",
# 	"Kula Korner", 
# 	"KulaPlus",
# 	"Kyheo Restaurant",
# 	"La Dolce Vita",
# 	"La Mesa Espanola",
# 	"Jupiter Guest Resort",
# 	"K lounge",
# 	"Kadai King",
# 	"Kamanga Bar & Restaurant",
# 	"Kamanga Bar & Restaurant",
# 	"Karen Country Lounge",
# 	"Katanazi Restaurant",
# 	"Kates Bakers",
# 	"Kavs Fruit & Juice",
# 	"Kebab Korner",
# 	"Ken Cafe",
# 	"Kenchic Inn",
# 	"Kendu",
# 	"Kengeles",
# 	"Kengeria Restaurant",
# 	"Kenpride Foods ltd",
# 	"Kentmere Club",
# 	"Keynan's & Kimmi's",
# 	"KFC",
# 	"Khazana",
# 	"Kingfisher Bar",
# 	"Kings",
# 	"Kipepeo",
# 	"Kivuli Grill",
# 	"Klique",
# 	"Kowloon Gardens Chinese",
# 	"KTDA Tea House",
# 	"Kula Korna",
# 	"Kula Korner",
# 	"KulaPlus", 
# 	"Kyheo Restaurant",
# 	"La Dolce Vita",
# 	"La Mesa Espanola",
# 	"La Pizzetta ",
# 	"La Prugna D'oro",
# 	"La Salumeria",
# 	"Laikiana",
# 	"Lal Qila Restaurant",
# 	"Langi Langi Restaurant & Bar",
# 	"Larena Pizzeria",
# 	"Le Bistrot",
# 	"Le Palanak",
# 	"Le Rustique",
# 	"Le Vans",
# 	"Legend Lounge",
# 	"Level 8",
# 	"Level One Pub & Restaurant",
# 	"Link Palace Pub & Restaurant",
# 	"Lirryz",
# 	"London Cafe",
# 	"Long Horn Pub & Restaurant",
# 	"LoRoad Delamere's Terrace",
# 	"LoRoad Erroll Restaurant",
# 	"Lowis Restaurant",
# 	"Lucca Restaurant",
# 	"Lulu",
# 	"Luna lounge",
# 	"Mac - Nats",
# 	"Macushla House",
# 	"Maharaja Restaurant",
# 	"Mamas Patisserie",
# 	"Mamba Village",
# 	"Mambo Italia",
# 	"Mandhari", 
# 	"Masrawy Egyptian Restaurant",
# 	"Mawar Cafeteria",
# 	"Max Land",
# 	"Mbugani Restaurant",
# 	"Mediterraneo", 
# 	"Mercury",
# 	"Misty Ginger",
# 	"Mitende Atrium",
# 	"Monikos Bistro",
# 	"Monikos Garden",
# 	"Moonlight Cafeteria",
# 	"Mughals ",
# 	"Muhibbah",
# 	"Murera Happy bar &restaurant",
# 	"Mvuli House Restaurant",
# 	"Myra's",
# 	"Mystique Gardens",
# 	"Nahrain",
# 	"Naked Pizza",
# 	"Nargis",
# 	"Natives Sports Bar & Grill",
# 	"Natures African Cuisine",
# 	"Nest",
# 	"New Jiang Su Restaurant",
# 	"New Maisha Restaurant",
# 	"Ngando The Place",
# 	"Ni Honjin",
# 	"Nyama Choma Ranch",
# 	"O Sinkirri",
# 	"Oasis", 
# 	"Ocean Basket",
# 	"Oceans Flavours",
# 	"Office Pub",
# 	"Ohoggans Bar & Restaurant",
# 	"Ojays Bar & Restaurant",
# 	"Ol Kiserian",
# 	"Open House",
# 	"Orbit Fast Foods",
# 	"Orchid Restaurant",
# 	"Oro restaurant",
# 	"Osteria",
# 	"Pablos Restaurant",
# 	"Paces Cafe",
# 	"Pampa", 
# 	"Pango Brasserie",
# 	"Paradise Cafe",
# 	"Park View Inn",
# 	"Patys Krispy Fries",
# 	"Peachez Fries Hotel",
# 	"Peecees Take Out",
# 	"Peppers Restaurant",
# 	"Peri Peri Grill",
# 	"Pete's Coffee",
# 	"Phoenician Restaurant",
# 	"Piano Bar",
# 	"Pitstop Bar and Restaurant",
# 	"Pizza Garden",
# 	"Pizza Inn",
# 	"Pizza Planet",
# 	"Planet Barbeque",
# 	"Planet Yogurt",
# 	"Plantation Cafe",
# 	"Plaza Cafe",
# "Polo Restaurant",
# "Pool Bar & Restaurant",
# "Pool Deck",
# "Pool Restaurant",
# "Pool Terrace",
# "Pool Terrance & Bar",
# "Pooldeck Panorama",
# "Pots and Palms",
# "Pots Delight",
# "Prime Cuts Butchery & Bistro",
# "Primi Piatti",
# "Promodoro",
# "Psys Restaurant",
# "Public Bar & Restaurant",
# "PuRoady Arms",
# "Pwani Pool Restaurant",
# "Que Pasa Bar & Bistro",
# "R & J Bistro",
# "Raha Fresh",
# "Ranalo Foods Ltd",
# "Rapma Eating House",
# "Rayan Restaurant",
# "Red Chilli Restaurant",
# "Red Garnet Restaurant",
# "Red Lion Club House",
# "Red Nova",
# "Red Office Lounge & Grill",
# "Red Sea",
# "Relish Restaurant",
# "Rendezvous Restaurant",
# "Revive",
# "Rezorous Bar & Restaurant",
# "Rib i Grillz",
# "RIM Club",
# "Rising Star Cafe & Restaurant",
# "River Café ",
# "Riverine Juices",
# "Road Runner",
# "Roberto's",
# "Rolfs Place",
# "Roro",
# "Royal Flavours Grille",
# "Royal Kitchen ",
# "Royal Sizzlers",
# "Ruby Lounge",
# "Rudy",
# "Safari Bar",
# "Safari Cafe",
# "Safari Restaurant",
# "Safari Terrace Bar",
# "Safe Lodge",
# "Saffron", 
# "Safi",
# "Sahara Garden Restaurant",
# "Sale E Pepe Restaurant",
# "Sams Pub & Restaurant",
# "Santa Fe Lounge and Grill",
# "Saporro",
# "Sarabi Pool & Supper Club",
# "Sarang Cafe & Restaurant",
# "Savanna Coffee Lounge",
# "Seasons Restaurant",
# "Secret geRoaden",
# "Serai Restaurant",
# "Seven Degrees",
# "Shabz Barbeque",
# "Shade Hotel",
# "Shine Cafe",
# "Siam Thai",
# "Sierra Brasseire",
# "Siesta Juice Bar",
# "Signature",
# "Sikia Fine Dining",
# "Simba Saloon",
# "Simmers",
# "Simon's Food",
# "Sippers Bar & Restaurant",
# "Six Flags",
# "Slims Restaurant",
# "Slurpy",
# "Slush Ltd",
# "Slush Tubman",
# "Sly's Cafe Pronto",
# "Smart Village Ltd",
# "Smokeys",
# "Smoothers",
# "Soaring Eagle Spur",
# "Sofis Deli",
# "Sofra",
# "Solar Gardens & Sports Bar",
# "SonfoRoad Limited",
# "Songea Restaurant",
# "Southern Fried Chicken",
# "Southern Fried Chicken",
# "Spice Roots",
# "Spice Roots",
# "Spinners Web Cafe",
# "Spoilers Lounge",
# "Spring Valley Oven",
# "Steak & Ale",
# "Steers",
# "Steffis Place",
# "Stenrace",
# "Street Kitchen",
# "Subway Kenya",
# "Subzone Restaurant",
# "Sundeck Pizzeria & Grill",
# "Sunrise Bridges Ltd",
# "Supreme Restaurant",
# "Sushi Bar",
# "Suya Spot",
# "wahili Plate",
# "Sweet Melon",
# "Taidys Restaurant",
# "Taj",
# "Talisman",
# "Tamambo",
# "Tamarid", 
# "Tambourin Restaurant",
# "Tamu Tamu Dishes",
# "Taste Of Africa",
# "Taste of China",
# "Tatu",
# "Tawa & Tandoor",
# "Teazers Westwise Lounge",
# "Technofrigo Coffee Bar",
# "Teenaz Restaurant",
# "Terrace",
# "Terry's Place",
# "Tesplace",
# "Test Cer Restaurant",
# "Thai Chi",
# "Thai Cuisine",
# "Thai Village",
# "The Balcony",
# "The Bedelle",
# "The Blues Restaurant",
# "The Chiyo ",
# "The Court YaRoad Gardens",
# "The Good Food Company",
# "The Jolly Roger Theme Park and Restaurant",
# "The Patio Restaurant",
# "The Smith Bar & Restaurant",
# "The Tea Room",
# "The Urban Spoon Restaurant",
# "The Wine Shop and Bar",
# "Thermo Restaurant",
# "Thorn Tree Café",
# "Tiamo Club & Lounge",
# "Tin Tin",
# "Tipuana",
# "Tokyo",
# "Travellers Restaurant",
# "Tree house Restaurant",
# "Tribeka Restaurant & Pub",
# "Tsavo Dishes",
# "Tulips Restaurant",
# "Tushibe",
# "Tutus Bar & Restaurant",
# "Under The Radar",
# "United Kenya Club",
# "Upper Hill Gardens Restaurant",
# "Urban Coffee",
# "Urban Eatery",
# "Utamaduni Restaurant",
# "Valley Coffee Shake",
# "Vamos Early & Late Bistro",
# "Vanela House of Coffees",
# "Vegi Veg Food",
# "Vegis Club",
# "Velvet Chocolate",
# "Victoria Cafe",
# "Vimac Restaurant",
# "VineyaRoad",
# "Visa Place",
# "Vista restaurant",
# "Viva Lounge Sports Bar & Restaurant",
# "Vogue Cafe",
# "Waka Waka Bar & Restaurant",
# "Wanjokis Tea Kiosk",
# "Wasanii Restaurant",
# "Wataalamu Restaurant",
# "Watercress",
# "Wilhaz Restaurant",
# "Wilhaz Restaurant",
# "Windsor Library Bar",
# "Windsor Room Restaurant",
# "Winner Pavilion",
# "Wonderland Restaurant",
# "WWW Wine Shop & Bar",
# "Xian Chinese Restaurant",
# "Ya Mike The Dinner",
# "Yummy Pies",
# "Zafferano Restaurant",
# "Zapata Restaurant",
# "Zaytoon Restaurant",
# "Zebra Lounge Bar & Grill",
# "Zinos Restaurant",
# "Albaik Kenya",
# "Amore Mia Restaurant",
# "Aqua Restaurant Nyali Beach Hotel",
# "Azad Fast food",
# "Barka Restaurant",
# "Bhagwanji Confectioners",
# "Big Tree Restaurant",
# "Bistro Mchana",
# "Blue Room",
# "Bobs Bar",
# "Bob's Sandwich Bar & Grill",
# "Bollywood Bites",
# "Cafe Mocha",
# "Cafe Nosh Nyali",
# "Canton Malaysian Chinese Restaurant",
# "Caribou Restaurant",
# "Cavern Beach Bistro",
# "Cocos Beach Bar",
# "Coffee Hut",
# "Creamy Inn",
# "Cuba Libre",
# "Debonairs",
# "Delight Grill & Barbeque",
# "Dormans Mombasa",
# "Eataly Restaurant",
# "Fishermans Cave Restaurant",
# "Fishermans Harvest Restaurant",
# "Flame Tree Restaurant",
# "Fountain Lounge at Nyali Beach Hotel",
# "Fountain Restaurant",
# "Galaxy Chinese Restaurant",
# "Galitos",
# "Golden Crust Ltd",
# "Haandi Black Bean",
# "Haandi Udupi",
# "Harry's Bar Nyali Beach Hotel",
# "Harvey's Fishette",
# "Hillpark Hotel Tiwi Beach",
# "Hunters Steak House",
# "Il Covo Bamburi Mombasa",
# "Il Covo Nyali Branch",
# "Imani Dhow",
# "Indo Africa Restaurant",
# "J.D's Bar and Restaurant",
# "Jahazi Seafood Grill",
# "Jai D's",
# "Kisima Restaurant",
# "Koroga Country Club",
# "La Pergola",
# "La Verandah",
# "Lido Restaurant",
# "Maharaja Restaurant",
# "Mi So Hi Chinese Take Away",
# "Mikaye Restaurant",
# "Minazi Restaurant",
# "Misono Japanese Restaurant",
# "MNKafe",
# "Mombasa Restaurant",
# "Moorings Floating Restaurant",
# "Msafiri Bar",
# "Mvita Grill at Nyali Beach Hotel",
# "Overseas Chinese Restaurant",
# "Papagayo",
# "Papillon Gardens Bar",
# "Paradise Corner",
# "Pavilion Restaurant",
# "Pitcher and Butch",
# "Pizza Inn",
# "Pontoon Restaurant and Bar Lounge",
# "Punjabi Dhaba",
# "Regal Corner",
# "Robertos Bamburi",
# "Robertos Nyali",
# "Rockwall Restaurant",
# "Rozina House Restaurant", 
# "Sai Rose Chinese Restaurant",
# "Sails Restaurant Nyali Beach hotel",
# "Sheba Restaurant & Lounge",
# "Sheesh Mahal Nyali Beach Hotel",
# "Shehnai Restaurant",
# "Sinbad Restaurant",
# "Singh Restaurant",
# "Splendid View Cafe",
# "Steers",
# "Tamarind Dhow",
# "Tamarind Mombasa",
# "Thalassa Restaurant & Lounge",
# "The Cake Haven",
# "Yuls Restaurant",
# "Espresso Coffee House Ltd",
# "Sana Cafeteria Ltd" ].each do |company|

# 		@restaurants = Industry.find_by_title("Restaurants")
# 	    restaurants_id = @restaurants.id

# 		Company.create(:title=>company,:industry_id=> restaurants_id)
# 	end




# [ "Afwan Medical Centre",
# 	"AAR",
# 	"Aga Khan University Hospital",
# 	"Angelic Hospital",
# 	"Avenue Healthcare",
# 	"Blessed Louis Palazzolo Health Centre",
# 	"Canan Health Services",
# 	"Central Park", 
# 	"Chiromo Lane Medical Centre",
# 	"City Nursing Home", 
# 	"Coptic Church Nursing",
# 	"Divine Word Parish Health Centre",
# 	"Donholm Maternity & Nursing Home",
# 	"Dorkcare Nursing Home Ltd",
# 	"Edelvale Trust Jamaa H Hospital",
# 	"Edianna Hospital",
# 	"Emmaus Nursing Home",
# 	"Enkitok Joy Nursing Home",
# 	"Family Access Medical Centre",
# 	"Family Health Options",
# 	"Gertrudes",
# 	"Guru Nanak Ramgarhia Sikh",
# 	"Health Ways Medical Centre",
# 	"Huruma Nursing & Maternity Home",
# 	"Kahawa Wendani", 
# 	"Kamiti Hospital",
# 	"Karen", 
# 	"Kasarani Nursing Home",
# 	"Kayole Hospital",
# 	"Kenyatta National Hospital",
# 	"Kenyatta University Referral", 
# 	"Kilimanjaro Nursing Home",
# 	"Komarock Modern", 
# 	"Ladnan", 
# 	"Langata", 
# 	"Lions Sight First Eye",
# 	"Madina", 
# 	"Magadi Soda Company", 
# 	"Maria Immaculate ",
# 	"Maria Nursing Home",
# 	"Mariakani Cottage",
# 	"Marie Stopes",
# 	"Marura Nursing Home",
# 	"Masaba", 
# 	"Matasia Health Clinic",
# 	"Mater Hospital", 
# 	"Mathare Mental", 
# 	"Mbagathi District ",
# 	"Melchizedek", 
# 	"Menelik Medical Centre",
# 	"Meridian Equator", 
# 	"Metropolitan Hospital",
# 	"Midhill Maternity & Nursing Home",
# 	"Mother & Child Hospital",
# 	"MP Shah Hospital", 
# 	"Muteithania Medical Clinic",
# 	"Nairobi Equator Hospital",
# 	"Nairobi Hospital Nairobi",
# 	"Nairobi South Medical Centre",
# 	"Nairobi West", 
# 	"Nairobi Women's",
# 	"National Spinal Injury", 
# 	"Neema", 
# 	"Ngumba Centre",
# 	"Olive Tree", 
# 	"Parklands Ambulatory Surgical Centre",
# 	"Parkroad Nursing Home", 
# 	"Pona Medical Clinic",
# 	"Prime Health Services",
# 	"Provider Medical Centre",
# 	"Pumwani", 
# 	"Radent Hospital",
# 	"Radiant",
# 	"Royal Gardens",
# 	"Salama Nursing & Maternity Home",
# 	"Samaritan Medical Services",
# 	"Sinai", 
# 	"South B Hospital",
# 	"St Catherine's Nursing home",
# 	"St. Agatha Medicare",
# 	"St. Annes Maternity Home",
# 	"St. John's Hospital",
# 	"St. Joseph Nursing Home",
# 	"St. Jude’s Healthcare & Maternity",
# 	"St. Marks Hospital",
# 	"St. Mary’s Mission Hospital",
# 	"St. Thomas Medical Health Services",
# 	"St.Francis Community Hospital",
# 	"Star General Medical Centre",
# 	"Umoja Hospital",
# 	"University Of Nairobi Health Services",
# 	"Uzima Dispensary And Maternity",
# 	"Victory Hospital",
# 	"Wentworth Hospital",
# 	"Bakarani Nursing Home",
# 	"Bomu Medical Centre",
# 	"Coast General Hospital", 
# 	"Jibana Health Centre",
# 	"Jocham Hospital",
# 	"Lady Griggs Maternity", 
# 	"Mainland Health Centre",
# 	"Mariakani Sub-District", 
# 	"Mary Immaculate Maternity", 
# 	"Mewa Medical Centre",
# 	"Mombasa Hospital", 
# 	"Nyali Paediatric Hospital",
# 	"Pandya Memorial Hospital",
# 	"Port Reitz District Hospital",
# 	"Rabai Rural Health ",
# 	"Sayyid Fatmah Hospital",
# 	"Shimo La Tewa Hospital", 
# 	"Makupa Hospital",
# 	"Tudor Healthcare",
# 	"Agape vct Centre",
# 	"Boya Rural Nursing Home",
# 	"Coptic Nursing Home Maseno",
# 	"Divine Mercy Aluor Health Centre",
# 	"Dophil Nursing & Maternity Home",
# 	"Dunga Maternity & Nursing Home",
# 	"Holy Family Catholic Mission", 
# 	"Jalaram Nursing & Maternity Home",
# 	"Kisumu District Hospital",
# 	"Kombewa District Hospital",
# 	"Maseno Hospital",
# 	"Milimani Maternity",
# 	"Nightgale Maternity", 
# 	"Ogra Medical Centre", 
# 	"Pandpieri Catholic Centre",
# 	"Provincial General Hospital",
# 	"Rachar Sugar Belt Nursing Home",
# 	"Siaya Medical Centre",
# 	"St. Consolata", 
# 	"St. Elizabeth Chiga Dispensary",
# 	"St. Joseph's Hospital", 
# 	"St. Lukes Medical Centre",
# 	"St. Monica's", 
# 	"Star Children Hospital",
# 	"The Port Florence Community",
# 	"Victoria Hospital" ].each do |company|

# 		@hospitals = Industry.find_by_title("Hospitals")
# 	    hospitals_id = @hospitals.id

# 		Company.create(:title=>company,:industry_id=> hospitals_id)
# 	end





# 	[ "Abson Motors",
# 	"Auto-Sueco", 
# 	"Autoxpress",
# 	"Bavaria Auto",
# 	"Car & General",
# 	"CMC Motors",
# 	"Dt Dobie",
# 	"Foton",
# 	"Hyundai",
# 	"General Motors",
# 	"Stantech Motors",
# 	"Tata Africa",
# 	"Toyota"].each do |company|

# 		@motor = Industry.find_by_title("Motor")
# 	    motor_id = @motor.id

# 		Company.create(:title=>company,:industry_id=> motor_id)
# 	end


# 	[ "Azizi Realtors",
# 	"Buyrent", 
# 	"Diamond City Villas",
# 	"Dunhill",
# 	"Gimco",
# 	"Hass Consultant",
# 	"Knight Frank",
# 	"Myspace Properties",
# 	"Nairobi Links",
# 	"Nairobi Real Estate",
# 	"NM Realise",
# 	"Pam Goldings",
# 	"Ryden International",
# 	"Tysons",
# 	"Villa Care"].each do |company|

# 		@real_estate = Industry.find_by_title("Real Estate")
# 	    real_estate_id = @real_estate.id

# 		Company.create(:title=>company,:industry_id=> real_estate_id)
# 	end



# 	[ "4u2",
# 	"Mr Price", 
# 	"Truworths",
# 	"Angelo",
# 	"Woolworths",
# 	"Avilas",
# 	"Clarks",
# 	"Bata",
# 	"Text Book Centre",
# 	"Nairobi Sports House",
# 	"Toy World",
# 	"Alibhai Shariff" ].each do |company|

# 		@retail = Industry.find_by_title("Retail")
# 	    retail_id = @retail.id

# 		Company.create(:title=>company,:industry_id=> retail_id)
# 	end


  
#   [ "Game Changer",
# 	"Fun Scapes", 
# 	"IMAX",
# 	"Fox Theatres",
# 	"Cinemax" ].each do |company|

# 		@entertainment = Industry.find_by_title("Entertainment")
# 	    entertainment_id = @entertainment.id

# 		Company.create(:title=>company,:industry_id=> entertainment_id)
# 	end


# 	[ "Optica",
# 	"Baus" ].each do |company|

# 		@opticians = Industry.find_by_title("Opticians")
# 	    opticians_id = @opticians.id

# 		Company.create(:title=>company,:industry_id=> opticians_id)
# 	end


# 	[ "Akamba",
# 	"Chania Genesis",
# 	"Coast Bus",
# 	"Crown Bus", 
# 	"Dolphin Coaches", 
# 	"Double M",
# 	"Dreamline",
# 	"Easy Coach",
# 	"Express Connections",
# 	"Gateway Bus",
# 	"Guardian Coach",
# 	"Horizon  Coach",
# 	"KBS",
# 	"Mash Bus",
# 	"Modern Coast",
# 	"Mololine",
# 	"Prestige Shuttle",
# 	"Simba coach",
# 	"Spanish Coach" ].each do |company|

# 		@bus_companies = Industry.find_by_title("Bus Companies")
# 	    bus_companies_id = @bus_companies.id

# 		Company.create(:title=>company,:industry_id=> bus_companies_id)
# 	end




#     [ "24/7 Cabs",
# 	"Able Travel",
# 	"Africabs Tours",
# 	"AIRCAB",
# 	"Alitex Enterprise",
# 	"Alpha-Cabs",
# 	"Ambassador Cabs",
# 	"Anush Cabs",
# 	"Arata Cabs",
# 	"Arcade Taxis",
# 	"Archer's Cabs",
# 	"Buzz A Cab",
# 	"Comfort Taxis",
# 	"Courtesy Cabs",
# 	"Delight cab",
# 	"Dial-A-Cab",
# 	"First Cab",
# 	"Genet Tours", 
# 	"Hilltop Taxis",
# 	"Iceberg Tours", 
# 	"Jambo Taxis",
# 	"Jatco Taxis",
# 	"Jimcab", 
# 	"Kenatco",
# 	"Kenyatta Market Taxis",
# 	"Link Taxis",
# 	"Mwalimu Taxis",
# 	"Neema Taxi", 
# 	"New Jambo Taxis",
# 	"Nyamuruthi SHG",
# 	"On Time Cabs",
# 	"Ongata Rongai Cabs",
# 	"Patcab Tours",
# 	"Prestige Taxis",
# 	"Princess Cabs",
# 	"Royal Cabs",
# 	"Stride Point ltd",
# 	"Topdeck Travel", 
# 	"Universal Cabs",
# 	"Wonderview Taxis",
# 	"Yaya Taxi Cabs",
# 	"Zuri Cabs" ].each do |company|

# 		@taxi_companies = Industry.find_by_title("Taxi Companies")
# 	    taxi_companies_id = @taxi_companies.id

# 		Company.create(:title=>company,:industry_id=> taxi_companies_id)
# 	end



#     [ "Interior and Coordination of National Government ",
# 	"Devolution and Planning",
# 	"The National Treasury",
# 	"Defence",
# 	"Foreign Affairs",
# 	"Education",
# 	"Health",
# 	"Transport and Infrastructure",
# 	"Information, Communication and Technology",
# 	"Environment, Water and Natural Resource",
# 	"Land, Housing and Urban Development",
# 	"Sports, Culture and the Arts",
# 	"Labour, Social Security and Services",
# 	"Industrialization and Enterprise Development",
# 	"Commerce, Tourism and East Africa Region",
# 	"Mining",
# 	"Agriculture, Livestock and Fisheries",
# 	"Central Bank of Kenya",
# 	"Kenya Power and Lighting Company",
# 	"City Council",
# 	"Nairobi City Water and Sewerage Company",
# 	"Enterprise Development Agency",
# 	"Export Promotion Council", 
# 	"Investment Promotion Centre",
# 	"Kenya Agriculture Development Corporation",
# 	"Kenya Airports Authority",
# 	"Kenya Anti Corruption Commission",
# 	"Kenya Broadcasting Corporation",
# 	"Kenya Bureau of Standards",
# 	"Kenya EPZ Authority",
# 	"Kenya Human Rights Commission",
# 	"Kenya Investment Authority", 
# 	"Kenya National Audit Office",
# 	"Kenya Port Authority",
# 	"Kenya Power & Lighting Co. Ltd", 
# 	"Kenya Railways Corporation",
# 	"Kenya Revenue Authority",
# 	"Kenya Tourism Development Corporation",
# 	"Kenya Tourist Board",
# 	"Kenya Wildlife Service",
# 	"Tea Board of Kenya",
# 	"Kenya Institute of Mass Communication",
# 	"National Treasury ",
# 	"Kenya Revenue authority",
# 	"Retirement Benefits Authority",
# 	"Kenya Re-Insurance Corp.",
# 	"Capital Markets Authority",
# 	"Consolidated Bank of Kenya",
# 	"Deposit Protection Fund Board",
# 	"Kenya Post Office savings Bank",
# 	"Kenya Accountants & Secretaries Examination Board (KASNEB)",
# 	"Kenya National Assurance (2001) Limited",
# 	"Central Bank of Kenya",
# 	"Capital Markets Tribunal",
# 	"State Corporations Appeals tribunal",
# 	"Kenya Institute for Public Policy Research and Analysis",
# 	"Ministry of water and natural resources",
# 	"National Water Conservation & Pipeline Corporation",
# 	"National Irrigation Board",
# 	"Kenya Water Institute",
# 	"Water Services Regulator Board",
# 	"Lake Victoria South Water Services Board",
# 	"Coast Water Services Board",
# 	"Northern Water Services Board",
# 	"Water Services Trust Fund",
# 	"Rift Valley Water Services Board",
# 	"Lake Victoria North Water Services Board",
# 	"Athi Water Services Board",
# 	"The Tana Water Services Board",
# 	"Water Resources Management Authority",
# 	"Ministry of Transport and Infrastructure",
# 	"Kenya Airports Authority",
# 	"Kenya Railways Corporation",
# 	"Kenya Ports Authority",
# 	"Kenya Ferry Services Limited",
# 	"Transport Licensing Board",
# 	"Kenya civil Aviation Authority",
# 	"Transport licensing Appeal Tribunal",
# 	"Kenya Roads Board",
# 	"Kenya National Shipping Line",
# 	"Ministry of Information, Communications& Technology (ICT)",
# 	"Communication Commission of Kenya",
# 	"Postal Corporation of Kenya",
# 	"Telkom Kenya Ltd.",
# 	"Kenya Broadcasting Corporation",
# 	"Kenya Film Commission",
# 	"The Kenya Information & Communication Technology",
# 	"Ministry of Agriculture, Livestock & Fisheries",
# 	"Tea Board of Kenya",
# 	"Pyrethrum Board of Kenya",
# 	"Horticultural Crops development authority",
# 	"Coffee Board of Kenya",
# 	"Agricultural Finance Corporation.",
# 	"National Cereals & Produce Board",
# 	"Kenya Plant Health Inspectorate Board",
# 	"Kenya Sugar board",
# 	"Nzoia Sugar Company",
# 	"Chemilil Sugar Company",
# 	"Kenya Sugar research foundation",
# 	"Pests control Products Board",
# 	"Central Agricultural Board",
# 	"Nyayo Tea Zones Development Corporation",
# 	"Agricultural development Corporation",
# 	"Kenya Seed Company",
# 	"Kenya Agricultural research Institute",
# 	"Coffee Research Foundation",
# 	"Tea research foundation",
# 	"Sugar Arbitration board",
# 	"Agricultural Information resource Centre",
# 	"Kenya Sisal Board",
# 	"Bukura Agricultural College",
# 	"Kenya dairy Board",
# 	"Kenya Meat commission",
# 	"Kenya Marine & Fisheries Research Institute",
# 	"Co-operative College of Kenya",
# 	"New Kenya Co-operative Creameries Ltd",
# 	"Ministry of Education",
# 	"National council for Science & Technology (NCST)",
# 	"Public Universities Inspection Board",
# 	"University of Nairobi",
# 	"Moi University",
# 	"Egerton University",
# 	"Jomo Kenyatta University of Agriculture & Technology",
# 	"Kenyatta University",
# 	"Maseno University",
# 	"Kenya National examination Council",
# 	"Kenya Literature Bureau",
# 	"Jomo Kenyatta Foundation",
# 	"Kenya Institute of Education",
# 	"Kenya Education staff Institute",
# 	"Commission for Higher Education",
# 	"Higher Education Loans Board",
# 	"Teacher’s Service Commission",
# 	"Western University College of science and Technology",
# 	"Ministry of Energy & Petroleum",
# 	"Kenya Power and Lighting Company",
# 	"Kenya Electricity Generating Company (KenGen)",
# 	"Kenya Pipeline Company",
# 	"National Oil Corporation of Kenya",
# 	"Kenya Petroleum Refinery",
# 	"Electricity Regulatory Board",
# 	"The Energy Tribunal",
# 	"Rural Electrification Authority",
# 	"Energy Regulatory Commission",
# 	"Ministry of Commerce & Tourism",
# 	"Kenya Tourist Development Corp",
# 	"Kenya Tourist Board",
# 	"Catering Training & Tourism Development levy Trustees",
# 	"Kenya Utalii College",
# 	"Kenya Wildlife Services",
# 	"Kenyatta International Conference Centre Corporation",
# 	"Hotels& Restaurants Authority",
# 	"Kenya Investment Authority",
# 	"Export Processing Zones Authority",
# 	"Ministry of Environment",
# 	"Kenya Forest Service",
# 	"Kenya Forestry Research Institute",
# 	"National Environmental Management authority",
# 	"Ministry of Industrialization and Enterprise Development",
# 	"Kenya National Trading Corporation",
# 	"Kenya Wine Agencies Limited",
# 	"Industrial & Commercial Dev. Corporation (ICDC)",
# 	"Industry Property Tribunal",
# 	"Numerical Machining Complex",
# 	"Anti-Counterfeiting Agency",
# 	"Kenya Industrial Property Institute",
# 	"Kenya Agricultural & Development Institute",
# 	"East Africa Portland Cement",
# 	"Kenya Industrial Estates",
# 	"Kenya Bureau of Standards",
# 	"Industrial Development Bank Capital Limited",
# 	"Ministry of Health",
# 	"Kenyatta National Hospital",
# 	"Kenya Medical Training College",
# 	"National Hospital Insurance fund",
# 	"Moi Teaching & Referral Hospital, Eldoret",
# 	"Kenya Medical Research institute",
# 	"Kenya Medical Supplies Agency",
# 	"Radiation Protection Board",
# 	"Ministry of Land, Housing and Urban Development",
# 	"National Housing Corporation",
# 	"Ewaso Ngiro North Development Authority",
# 	"Lake Basin Development Authority",
# 	"Coastal Development Authority",
# 	"Kerio Valley Development Authority",
# 	"Tana & Athi River Development Authority",
# 	"National Sports Stadia Management Authority",
# 	"Kenya Cultural Centre",
# 	"Kenya National Library services",
# 	"National Disability Council",
# 	"Gender Commission",
# 	"Public Archives Advisory Council"
# 	 ].each do |company|

# 		@government = Industry.find_by_title("Government")
# 	    government_id = @government.id

# 		Company.create(:title=>company,:industry_id=> government_id)
# 	end




#     [ "Headquarters(Vigilance House)",
# 	"Anti-Terrorist",
# 	"Adungosi Police Station",
# 	"Ahero Police Station",
# 	"Amagoro OCPD",
# 	"Arror Police Station",
# 	"Bahati Police Station",
# 	"Bamburi Police Station",
# 	"Baricho Police Station",
# 	"Baringo OCPD Office",
# 	"Bondo OCPD’s Office",
# 	"Bura Police Station",
# 	"Burubru",
# 	"Buru Buru",
# 	"Buru Buru OCPD",
# 	"Buru Buru Police Station",
# 	"Butere OCPD Office",
# 	"Butere Police Station",
# 	"Coast County Headquarters",
# 	"Capital Hill Post",
# 	"Central PPO Office",
# 	"Changamwe Police Station",
# 	"Cherangani Police Station",
# 	"Chesikaki Police Station",
# 	"Chuka Police Station",
# 	"Diani Police Station",
# 	"Eldoret Police Station",
# 	"Elementaita Police Post",
# 	"Elwark Police Station",
# 	"Embakasi OCPD",
# 	"Funyula Police Station ",
# 	"Garbatulla Police Station",
# 	"Garissa Hotline",
# 	"Gatundu Police Station",
# 	"Gilgil Police Station",
# 	"Githumu Police Station",
# 	"Githunguri Police Station",
# 	"Griftu Police Station",
# 	"ucha OCPD Office",
# 	"Highway Patrol Unit",
# 	"Hardy Police Station",
# 	"Hola Police Station Hola",
# 	"Homabay OCPD Office",
# 	"Igoji Police Post",
# 	"Ijara OCPD Office",
# 	"Ijara Police",
# 	"Jamhuri Police Post",
# 	"Jogoo Police Station",
# 	"Juja Police Station",
# 	"Kabati Police Station",
# 	"Kabete",
# 	"Kabras Police Station",
# 	"Kahawa Sukari",
# 	"Kahuro Police Station",
# 	"Kakamega OCPD Office",
# 	"Kanangop Police Station",
# 	"Kandara Police Station",
# 	"Kangema Police Station",
# 	"Kaptembwa Police Station",
# 	"Kapsokwony Police Station",
# 	"Kapsowar Police Station",
# 	"Kaptagat Police Station",
# 	"Karatina Police Station",
# 	"Karen Police Station",
# 	"Kariene Police Station",
# 	"Karuri Police Station",
# 	"Kasarani Police Station",
# 	"Kasarani Police Station",
# 	"Keiyo OCPD Office",
# 	"Kenyatta Police Post",
# 	"Kericho OCPD Office",
# 	"Kericho POLICE Station",
# 	"Keroka Police Station",
# 	"Kianyaga Police Station",
# 	"Kibwezi Police Station",
# 	"Kiganjo Police Station",
# 	"Kigumo Police Station",
# 	"Kigumo Police Station House",
# 	"Kiirua Police Station",
# 	"Kijabe Police Station",
# 	"Kijipwa Police Station",
# 	"Kikuyu Police Station",
# 	"Kileleshwa",
# 	"Kilgoris",
# 	"Kilifi OCPD Office",
# 	"Kilimani D/OCPD",
# 	"Kilimani OCPD",
# 	"Kilindini Division/OCS Port",
# 	"Kilimani Police Station",
# 	"Kilome Police Station",
# 	"Kimende Patrol Base",
# 	"Kimilili Police Station",
# 	"Kiminini Police Station",
# 	"Kinango Police Station",
# 	"Kipipiri Police Station",
# 	"Kipkabus OCPP",
# 	"Kiriani Police Post",
# 	"Kirinyaga OCPD Office",
# 	"Kisumu OCPD’s Office",
# 	"Kitale Hotline",
# 	"Kitui Division",
# 	"Koru Police Station",
# 	"Kuria OCPD’s",
# 	"Kwale OCPD Office",
# 	"Kwhisero OCPP",
# 	"Kyuso Police Station",
# 	"Lamu OCPD Office",
# 	"Lanet Police Station",
# 	"Langata OCPD",
# 	"Lari Police Station",
# 	"Likoni Police Station",
# 	"Lolgorian Police Station",
# 	"Luanda Police Station",
# 	"Lugari OCPD Office",
# 	"Lugari OCPP",
# 	"Lungalunga",
# 	"Lwala Police Station",
# 	"Madogo Police Station",
# 	"Magumu Police Post",
# 	"Makongeni",
# 	"Makupa Police Station",
# 	"Malaba Police Station",
# 	"Malakisi Police Station",
# 	"Malindi OCPD Office",
# 	"Malindi Police Station",
# 	"Mandera OCPD Office",
# 	"Maragua OCPD Office",
# 	"Maragua Police Station",
# 	"Marakwet OCPD Office",
# 	"Mariakani Police Station",
# 	"Marigat Police Station",
# 	"Masalani",
# 	"Mathare",
# 	"Matunda Police Station",
# 	"Maua Police Station",
# 	"Mbaraki Depot",
# 	"Mbooni Police Station",
# 	"Menengai Police Station",
# 	"Merti Police Station",
# 	"Meru North OCPD Office",
# 	"Meru South OCPD Office",
# 	"Migwani Police Station",
# 	"Mikinduri Police Station",
# 	"Milangine Police Station",
# 	"Modogashe Police Station",
# 	"Moi’s Bridge Police Station",
# 	"Molo OCPD Office",
# 	"Mombasa Central Police Station",
# 	"Mombasa Headquarters",
# 	"Mombasa Urban OCPD Office",
# 	"Moyale Police Station",
# 	"Msambweni Police Station",
# 	"Mt Elgon OCPD Office",
# 	"Mtitu Andei Police Station",
# 	"Mukurwe-Ini Police Station",
# 	"Muhoroni Divisional Headquarters",
# 	"Mumias Police Station",
# 	"Muranga South Division Hotline",
# 	"Muthaiga Police Station",
# 	"Mweiga Police Station",
# 	"Mwingi OCPD Office",
# 	"Mwingi Pabx",
# 	"Mbeere Division HQTS",
# 	"Machakos Division",
# 	"Mwingi Police Station",
# 	"Nairobi County Headquarters",
# 	"Nairobi Central OCPD",
# 	"Nairobi Central Police Station",
# 	"Nairobi Industrial Area",
# 	"Naivasha",
# 	"Naivasha OCPD Office",
# 	"Nakuru Police Station",
# 	"Narok OCPD Office",
# 	"Narok Police Station",
# 	"Naromoru Police Station",
# 	"Nchiru Police Station",
# 	"Ndaragwa Police Station",
# 	"Ngomongo",
# 	"Ngubi Patrol Base",
# 	"Njabini Police Station",
# 	"Njoro Police Station",
# 	"Nkubu Police Station",
# 	"Ntumu Police Station",
# 	"Nyahururu Police Station",
# 	"Nyali Police Station",
# 	"Nyakach Divisional Headquarters",
# 	"Nyamira Hotline",
# 	"Nyamira OCPD",
# 	"Nyamira Police Station",
# 	"Nyandarua Hotline",
# 	"Nyando OCPD",
# 	"Ngong Police Station",
# 	"Nyeri Hotline",
# 	"Ol Joro Orok Police Station",
# 	"Ol Kalou Police Station",
# 	"Othaya Police Station",
# 	"Pangani Police Station",
# 	"Pap Onditi Police Station",
# 	"Parklands Police Station",
# 	"Port Victoria Police",
# 	"Rachuonyo OCPD’s Office",
# 	"Rhamu Police Station",
# 	"Riruta Police Station",
# 	"Ruiru Police Station",
# 	"Runyenjes Police Station",
# 	"Rweno Police Post",
# 	"Saba Saba Police Post",
# 	"Sagana Police Station",
# 	"Salama Police Station",
# 	"Serem Police Station",
# 	"Sericho Police Station",
# 	"Shauri Moyo",
# 	"Siaya",
# 	"Siaya OCPD’s Office",
# 	"Solai Police Station",
# 	"Sololo Police Station",
# 	"Spring Valley",
# 	"Subukia Police Station",
# 	"Sultan Hamud Police Station",
# 	"Taita Taveta OCPD Office",
# 	"Taita Taveta Police Station",
# 	"Tambach Police Station",
# 	"Tana OCPD Office",
# 	"Taru",
# 	"Taveta Police Station",
# 	"Thika Police Station",
# 	"Thindigua Patrol Base",
# 	"Tigania Police Station",
# 	"Tigoni Police Station",
# 	"Timau Police Station",
# 	"Tot Police Station",
# 	"Trans-Mara OCPD",
# 	"Turbo Police Station",
# 	"Ukwala Police Station",
# 	"Vihiga OCPD Office",
# 	"Voi Police Station",
# 	"Wajir OCPD Office",
# 	"Wajir Police Station",
# 	"Wanguru Police Station",
# 	"Watamu Police Statio",
# 	"Webuye Police Station",
# 	"Wundanyi Police Station",
# 	"Yala Police Station" ].each do |company|

# 		@police = Industry.find_by_title("Police")
# 	    police_id = @police.id

# 		Company.create(:title=>company,:industry_id=> police_id)
# 	end
   


# 	["Kisumu",
# 		"Mombasa",
# 		"Nairobi",
# 		"Eldoret",
# 		"Coast",
# 		"Lokichogio",
# 		"Malindi",
# 		"Wajir",
# 		"Ukunda" ].each do |town|
# 			Town.create(:title=>town)
# 		end



# # [ "ABC Bank House",
# # 	"Westlands",
# # 	"Koinange Street",
# # 	"Industrial Area",
# # 	"Jubilee House",
# # 	"Centre Square",
# # 	"Kisumu",
# # 	"Oginga Odinga Road",
# # 	"Tivoli Centre Road",
# # 	"Kisumu East",
# # 	"United Mall",
# # 	"Mega Plaza",
# # 	"Angwana",
# # 	"Kisumu Al-Imrani",
# # 	"Giro House",
# # 	"Amalo Plaza",
# # 	"Kisumu Airport",
# # 	"Kisumu West",
# # 	"Kenya Re-Insurance Plaza"].each do |location|
# # 		@kisumu = Town.find_by_title("Kisumu")
# # 	    kisumu_id = @kisumu.id

# # 	Location.create(:title=>location,:town_id=>kisumu_id)
# #     end


#     [ "Oginga Odinga Road",
# 	"Mega City",
# 	"Oginga Odinga Road",
# 	"Tivoli Centre",
# 	"United Mall",
# 	"Re-insurance Plaza",
# 	"Mega Plaza",
# 	"Kenyatta Highway",
# 	"Tivoli Centre",
# 	"Jubilee House",
# 	"Angawa Avenue",
# 	"Oginga Odinga Street",
# 	"Ondiek Highway",
# 	"Jomo Kenyatta Highway",
# 	"Nyalenda",
# 	"Achieng Oneko Road",
# 	"Ondiek Highway",
# 	"Paul Mbuya Road",
# 	"Harambee Road",
# 	"Nzoia Road",
# 	"Mahia Street",
# 	"Omolo Agar Road",
# 	"Jomo Kenyatta Highway",
# 	"Lake Victoria",
# 	"Kisumu International Airport",
# 	"Wabera Street",
# 	"Winam",
# 	"Busia Road",
# 	"Ahero Aswani Road",
# 	"Luanda",
# 	"Alaka",
# 	"Dunga",
# 	"Kakamega Road",
# 	"Kombewa",
# 	"Maseno",
# 	"Kibos Road",
# 	"Milimani",
# 	"Ring Road",
# 	"Muhoroni",
# 	"Siaya",
# 	"Nyabondo",
# 	"Ramogi Road",
# 	"Ridoch Road",
# 	"Obote Road",
# 	"Mega City Complex",
# 	"Kenyatta Avenue",
# 	"Bank Road",
# 	"Bank Street",
# 	"Enterprise Road" ].each do |location|
# 		@kisumu = Town.find_by_title("Kisumu")
# 	    kisumu_id = @kisumu.id

# 	Location.create(:title=>location,:town_id=>kisumu_id)
#     end





#     [ "Nkrumah Road",
# 	"Nyali",
# 	"Moi Avenue",
# 	"Nyerere Avenue",
# 	"Moi International Airport",
# 	"Nkrumah Road",
# 	"Mombasa",
# 	"Diani",
# 	"Nyali",
# 	"Haile Selassie Road",
# 	"Digo Road",
# 	"Bamburi",
# 	"Ukunda",
# 	"Mt Kenya Road",
# 	"Kikambala",
# 	"TSS Tower",
# 	"City Mall",
# 	"Moyne Drive",
# 	"Fatemi House",
# 	"Mwembe Tayari",
# 	"Mfangano Road",
# 	"Engen Nyali Service Station",
# 	"Tudor Creek",
# 	"Mogadishu Road",
# 	"Mvita",
# 	"Likoni",
# 	"Changamwe",
# 	"Tononoka",
# 	"Kaloleni",
# 	"Kisauni",
# 	"Abdel Nasser Road",
# 	"Changamwe",
# 	"Kaloleni",
# 	"Mazeras",
# 	"Malupa",
# 	"Tudor",
# 	"Mnazi Moja Road",
# 	"Bnakele Road",
# 	"Nkrumah Road",
# 	"Mwembe Tayari Road",
# 	"Old Nairobi Road",
# 	"Jomo Kenyatta Avenue",
# 	"Kenyatta Avenue",
# 	"Makupa" ].each do |location|
# 		@mombasa = Town.find_by_title("Mombasa")
# 	    mombasa_id = @mombasa.id

# 	Location.create(:title=>location,:town_id=>mombasa_id)
#     end


#    [ "ABC Bank House",
# 	"Westlands",
# 	"Libra House",
# 	"Reinsurance Plaza",
# 	"Galleria Shopping Mall",
# 	"Greenspan Mall",
# 	"Upper Hill",
# 	"Lunga Lunga Road",
# 	"Kenyatta Avenue",
# 	"Baroda House",
# 	"Industrial Area",
# 	"Avon Centre",
# 	"ABC Place",
# 	"Bunyala Road",
# 	"Buru Buru",
# 	"Eastleigh", 
# 	"Enterprise Road", 
# 	"Gikomba", 
# 	"Haile Selassie", 
# 	"Harambee", 
# 	"Karen", 
# 	"Kawangware", 
# 	"Moi Avenue",  
# 	"South C", 
# 	"Nairobi West", 
# 	"Nakumatt Embakasi", 
# 	"Parklands", 
# 	"Rahimtulla Trust Towers",
# 	"River Road",  
# 	"Village Market",  
# 	"Industrial Area",
# 	"Jubilee House",
# 	"Centre Square",
# 	"Kisumu",
# 	"Oginga Odinga Road",
# 	"Tivoli Centre Road",
# 	"Kisumu East",
# 	"United Mall",
# 	"Mega Plaza",
# 	"Angwana",
# 	"Kisumu Al-Imrani",
# 	"Giro House",
# 	"Amalo Plaza",
# 	"Kisumu Airport",
# 	"Kisumu West",
# 	"Kenya Re-Insurance Plaza",
# 	"Chiromo",
# 	"Harambee Avenue",
# 	"Industrial Area",
# 	"Karen",
# 	"Riverside Mews",
# 	"Nairobi City Centre", 
# 	"Village Market", 
# 	"Eastleigh",
# 	"Donholm", 
# 	"Delta",
# 	"Diamond Plaza", 
# 	"Elite Banking Centre",
# 	"Sameer Park", 
# 	"Strathmore",
# 	"UN Gigiri",
# 	"Mama Ngina",
# 	"Mombasa Road",
# 	"Swissport",
# 	"Wabera",
# 	"Mamlaka",
# 	"Industrial Area",
# 	"Hilton",
# 	"Junction Mall",
# 	"Harambee Avenue",
# 	"Umoja",
# 	"City Hall",
# 	"Co-Op House",
# 	"Dandora",
# 	"Donholm", 
# 	"Eastleigh", 
# 	"Embakasi Junction", 
# 	"Gikomba", 
# 	"Industrial Area", 
# 	"Kangemi", 
# 	"Karen", 
# 	"Kariobangi", 
# 	"Kawangware", 
# 	"Kawangware 46", 
# 	"Kayole", 
# 	"Langata Road", 
# 	"Nacico", 
# 	"Nairobi Business Centre",
# 	"Parliament Road", 
# 	"Ruaka", 
# 	"Tom Mboya", 
# 	"Ukulima Co-Op House", 
# 	"Umoja", 
# 	"University Way", 
# 	"Wakulima", 
# 	"Mercantile House",
# 	"Nation Centre",
# 	"Capital Centre",
# 	"Eastleigh",
# 	"Prestige Plaza",
# 	"Otc",
# 	"Crossroad",
# 	"Madina Mall",
# 	"Ecobank Chambers",
# 	"Ecobank Towers",
# 	"Plaza 2000",
# 	"Westminster",
# 	"Equatorial Fidelity Centre",
# 	"Chester House",
# 	"Market",
# 	"Nairobi University",
# 	"Plaza Business Centre",
# 	"Sarit Centre",
# 	"Waiyaki Way",
# 	"Yaya Centre",
# 	"Harambee Avenue",
# 	"Industrial Area",
# 	"Community",
# 	"Mayfair",
# 	"Ruai",
# 	"Kilimani",
# 	"Kenpipe Plaza",
# 	"Four Ways",
# 	"Gikomba",
# 	"Kahawa House",
# 	"Kenyatta University",
# 	"Iambus",
# 	"Kikuyu",
# 	"Kimathi",
# 	"Knut House",
# 	"Lavington Supreme",
# 	"Family Bank Towers",
# 	"Cargen House",
# 	"Dagoreti",
# 	"Kiambu",
# 	"KTDA Plaza",
# 	"Sonalux",
# 	"Kaunda Street",
# 	"New Muthaiga",
# 	"Eastleigh-United Textile Centre",
# 	"Eastleigh-Gen Warungu Street",
# 	"Garissa",
# 	"South C",
# 	"Guardian Centre",
# 	"Geminia Plaza Upper Hill",
# 	"Eastleigh Main-Gen Wariunge Street",
# 	"Eastleigh-Jam Street",
# 	"Habib House",
# 	"2nd Ngong Avenue",
# 	"Langata Link",
# 	"Panari Centre",
# 	"Riverside Drive",
# 	"Wilson Airport",
# 	"Highridge",
# 	"Haile Selassie",
# 	"Greenspan Mall",
# 	"Banana",
# 	"GaRoaden Plaza",
# 	"Capital Hill",
# 	"Mombasa Road",
# 	"Haile Selassie",
# 	"Hurlingham",
# 	"Jogoo Road Nairobi",
# 	"Kick",
# 	"Kipande House",
# 	"Nairobi High Court",
# 	"Prestige Plaza",
# 	"Salama House Mortgage Centre",
# 	"Thika Road Mall",
# 	"UN Gigiri",
# 	"University Way",
# 	"Westgate Advantage",
# 	"K-rep Centre Kilimani",
# 	"Mebank Tower",
# 	"National Bank Building",
# 	"Hospital",
# 	"Inland Container Depot",
# 	"Times Towers",
# 	"Masaba Road",
# 	"Thika Road Mall",
# 	"Greenspan Mall",
# 	"Muthaiga",
# 	"Ukay Centre",
# 	"Warwick Centre",
# 	"Woodvale Grove Road",
# 	"City Hall Way",
# 	"Kirinyaga Road",
# 	"Munyu Road",
# 	"Enterprise Centre",
# 	"Williamson House",
# 	"Roysambu Road",
# 	"Mountain Mall",
# 	"Tom Mboya Street",
# 	"Afya Centre",
# 	"Apollo Centre",
# 	"Loita Street",
# 	"Lap Trust House",
# 	"Union Towers",
# 	"Re-Insurance Plaza",
# 	"Corporate Place",
# 	"Ambank House",
# 	"Panafric House",
# 	"Milimani Road",
# 	"Mamlaka Road",
# 	"Chiromo Road",
# 	"Bishop Magua Centre",
# 	"Tumaini House",
# 	"Jubilee Insurance House",
# 	"Kenindia House",
# 	"Contrast building",
# 	"Ngong Road",
# 	"Mayfair Centre",
# 	"Eco Bank Towers",
# 	"International House",
# 	"Solar House",
# 	"Prudential Assurance Building",
# 	"Shelter Afrique Branch",
# 	"Pan Africa House",
# 	"Uniafric House",
# 	"Pioneer House",
# 	"Finance House",
# 	"Queensway House",
# 	"Lenana Road",
# 	"Bishops Road",
# 	"Parklands Avenue",
# 	"Development House",
# 	"Njengi House",
# 	"GPO",
# 	"Telkom Plaza",
# 	"Extelcoms House",
# 	"T-Mall",
# 	"Wendani",
# 	"Uhuru Highway",
# 	"Mwanzi Road",
# 	"Aga Khan Walk",
# 	"Jogoo Rd",
# 	"Koinange Street",
# 	"Ngong",
# 	"Taj Mall",
# 	"Ronald Ngala Street",
# 	"Ruaraka",
# 	"South B",
# 	"Matasia",
# 	"Mfangano Street",
# 	"Mondlane Street",
# 	"Sheikh Karume Road",
# 	"Thigiri Ridge Road",
# 	"Thika-Kenyatta Highway",
# 	"Thika-Uhuru Street",
# 	"Head Office-Lenana Road",
# 	"Highridge- Diamond Plaza",
# 	"Highridge-Parklands",
# 	"Oilibya Plaza",
# 	"Yaya",
# 	"Lusaka Road",
# 	"Woodvale Grove",
# 	"Harry Thuku Road",
# 	"Embakasi",
# 	"Mbagathi Ridge",
# 	"CBD",
# 	"Muindi Mbingu street",
# 	"Lillian Towers",
# 	"General Waruingi St",
# 	"Kitale Ln",
# 	"Ralph Bunche",
# 	"Valley Road",
# 	"Gandhi Avenue",
# 	"Milimani",
# 	"Ndeni Road",
# 	"Gigiri",
# 	"Ridgeways",
# 	"Lagos Road",
# 	"Kasarani",
# 	"Monrovia Street",
# 	"Tsavo Lane",
# 	"Ralph Bunche Road",
# 	"Mlolongo",
# 	"Red Cross Road",
# 	"Daidai Road",
# 	"International Life House",
# 	"Hilton Hotel",
# 	"Bruce House",
# 	"Laico Regency Hotel",
# 	"Barclays Plaza",
# 	"Regal Plaza",
# 	"JKIA",
# 	"Valley Arcade",
# 	"Ojijo Road",
# 	"Kahawa West",
# 	"Riruta",
# 	"Lavington",
# 	"Pangani",
# 	"komarock",
# 	"Ngara",
# 	"Huruma",
# 	"Kahawa Wendani",
# 	"Major Kinyajui Street",
# 	"Langata",
# 	"Kibera",
# 	"Kenyatta Market",
# 	"Adams Arcade",
# 	"Ngumo Estate",
# 	"Naivasha Road",
# 	"Githurai",
# 	"Tena Estate",
# 	"Zimmerman",
# 	"UON",
# 	"North Airport Road",
# 	"Argwings Kodhek Road",
# 	"Kindaruma Road",
# 	"Limuru Road",
# 	"New Rehema House",
# 	"Sassini House",
# 	"College House",
# 	"Ongata Rongai",
# 	"Dagoretti Road",
# 	"Athi River",
# 	"Juja",
# 	"Biashara Street",
# 	"Kitengela",
# 	"City Centre",
# 	"Roysambu",
# 	"Madaraka",
# 	"Bnakele Road",
# 	"View Park Towers",
# 	"Lornho House",
# 	"Chaka Road",
# 	"Kijabe Street",
# 	"Kimathi Street",
# 	"Woodley",
# 	"Anniversary Towers",
# 	"Kampala Road",
# 	"Stima Plaza",
# 	"Kilimo House",
# 	"Works Building",
# 	"Utalii House",
# 	"Teleposta Towers",
# 	"Social Security House",
# 	"Kencom House",
# 	"Uchumi House",
# 	"Telposta Towers",
# 	"Transcom House",
# 	"Old Treasury Building",
# 	"Lenana Road ",
# 	"Treasury Building",
# 	"Showbe Plaza" ].each do |location|
# 		@nairobi = Town.find_by_title("Nairobi")
# 	    nairobi_id = @nairobi.id

# 	Location.create(:title=>location,:town_id=>nairobi_id)
#     end


 


#     [ "National Bank Building",
# 	"Eldoret International Airport" ].each do |location|
# 		@eldoret = Town.find_by_title("Eldoret")
# 	    eldoret_id = @eldoret.id

# 	Location.create(:title=>location,:town_id=>eldoret_id)
#     end


#     ["Mombasa"].each do |location|
# 		@coast = Town.find_by_title("Coast")
# 	    coast_id = @coast.id

# 	Location.create(:title=>location,:town_id=>coast_id)
#     end


#     ["Lokichogio Airport"].each do |location|
# 		@lokichogio = Town.find_by_title("Lokichogio")
# 	    lokichogio_id = @lokichogio.id

# 	Location.create(:title=>location,:town_id=>lokichogio_id)
#     end


#     ["Malindi Airport"].each do |location|
# 		@malindi = Town.find_by_title("Malindi")
# 	    malindi_id = @malindi.id

# 	Location.create(:title=>location,:town_id=>malindi_id)
#     end


#     ["Wajir Airport"].each do |location|
# 		@wajir = Town.find_by_title("Wajir")
# 	    wajir_id = @wajir.id

# 	Location.create(:title=>location,:town_id=>wajir_id)
#     end


#     ["Ukunda Airport"].each do |location|
# 		@ukunda = Town.find_by_title("Ukunda")
# 	    ukunda_id = @ukunda.id

# 	Location.create(:title=>location,:town_id=>ukunda_id)
#     end



# page = Page.new(:name=>"About us", :title=> "About Xemaxema",
#              :description => "Lorem ipsum", :slug => "about-xemaxema")
# puts page.save!(:validates=>false)


# page = Page.new(:name=>"About us", :title=> "Importance of feedback",
#             :description => "Genuine customer feedback provides extremely valuable insight for businesses. Both good and bad feedback is essential. It facilitates companies to correct errors, better the good and keep up with the consumer trends. More often than not it is an all-round value adding process.

# However research shows that for every customer complaint there are 26 other unhappy customers who remained silent. This proves that little feedback is given by customers. Frustrating process, distrust for follow up on feedback given, lengthy … , are among other challenges faced by customers giving feedback.

# A public feedback platform will eliminate some of the problems in that it is independent, less biased, allows sharing, transparent and possibly faster against one on one feedback. This will better the overall effect on customer service and value creation.

# Kenya does not have a forum like this, leaving companies not accountable and paying less attention on customer service. We would like to challenge and change this. {Name} is the platform that will give the customer in Kenya the chance to give ratings, Kudos and also challenge those that do not deliver. Customers are therefore encouraged … Come all let's give a ranking. We deserve better!",:slug=>"importance-of-feedback")

# page.save(:validates=>false)

# page = Page.new(:name=>"About us", :title=> "How we work",
#             :description => "Genuine customer feedback provides extremely valuable insight for businesses. Both good and bad feedback is essential. It facilitates companies to correct errors, better the good and keep up with the consumer trends. More often than not it is an all-round value adding process.

# However research shows that for every customer complaint there are 26 other unhappy customers who remained silent. This proves that little feedback is given by customers. Frustrating process, distrust for follow up on feedback given, lengthy … , are among other challenges faced by customers giving feedback.

# A public feedback platform will eliminate some of the problems in that it is independent, less biased, allows sharing, transparent and possibly faster against one on one feedback. This will better the overall effect on customer service and value creation.

# Kenya does not have a forum like this, leaving companies not accountable and paying less attention on customer service. We would like to challenge and change this. {Name} is the platform that will give the customer in Kenya the chance to give ratings, Kudos and also challenge those that do not deliver. Customers are therefore encouraged … Come all let's give a ranking. We deserve better!",:slug=>"how-we-work")
# page.save(:validates=>false)

# page = Page.new(:name=>"About us", :title=> "Terms of use",
#             :description => "Genuine customer feedback provides extremely valuable insight for businesses. Both good and bad feedback is essential. It facilitates companies to correct errors, better the good and keep up with the consumer trends. More often than not it is an all-round value adding process.

# However research shows that for every customer complaint there are 26 other unhappy customers who remained silent. This proves that little feedback is given by customers. Frustrating process, distrust for follow up on feedback given, lengthy … , are among other challenges faced by customers giving feedback.

# A public feedback platform will eliminate some of the problems in that it is independent, less biased, allows sharing, transparent and possibly faster against one on one feedback. This will better the overall effect on customer service and value creation.

# Kenya does not have a forum like this, leaving companies not accountable and paying less attention on customer service. We would like to challenge and change this. {Name} is the platform that will give the customer in Kenya the chance to give ratings, Kudos and also challenge those that do not deliver. Customers are therefore encouraged … Come all let's give a ranking. We deserve better!",:slug=>"terms-of-use")
# page.save(:validates=>false)


# page = Page.new(:name=>"How to write a good review:", :title=> "How to write a good review",
#             :description => "",:slug=>"how-to-write-good-review")
# page.save(:validates=>false)

# page = Page.new(:name=>"csr",  :title=>"CSR", :slug=>"csr",:template_name=>'csr')
# page.save(:validates=>false)
# ResourceType.create(:name=>"Jobs")
# ResourceType.create(:name=>"Articles")


# Seo.create(
# 	:meta_title => "Customer Support xemasupport", 
# 	:meta_description => "Genuine customer feedback provides extremely valuable insight for businesses. Both good and bad feedback is essential. It facilitates companies to correct errors, better the good and keep up with the consumer trends. More often than not it is an all-round value adding process.

# However research shows that for every customer complaint there are 26 other unhappy customers who remained silent. This proves that little feedback is given by customers. Frustrating process, distrust for follow up on feedback given, lengthy … , are among other challenges faced by customers giving feedback.

# A public feedback platform will eliminate some of the problems in that it is independent, less biased, allows sharing, transparent and possibly faster against one on one feedback. This will better the overall effect on customer service and value creation.

# Kenya does not have a forum like this, leaving companies not accountable and paying less attention on customer service. We would like to challenge and change this. {Name} is the platform that will give the customer in Kenya the chance to give ratings, Kudos and also challenge those that do not deliver. Customers are therefore encouraged … Come all let's give a ranking. We deserve better!", 
# 	:meta_keyword => "Customer support, xema, xemasupport")


# ["Dr. Eric Kahugu",
# "Dr. Ernest Muide",
# "Dr. Eva W. Njenga",
# "Dr. Marx M.O. Okonji",
# "Dr. Samuel MG Mwinzi",
# "Prof. Michael Sajabi Masinde",
# "Dr. Mauro Saio",
# "Dr. Noah W. Nganga",
# "Dr. Rohit Radia",
# "Dr. Evelyn G. Wagaiyu",
# "Mr. Maurice Wambani",
# "Dr. Shabbir Hussain",
# "Dr. Martin Luther Oduori",
# "Mr. S.R. Patel",
# "Dr. Jigisha Pankaj Jani",
# "Prof. Godfrey Nsereko Lule",
# "Mr. S.R. Patel",
# "Dr. Daniel Muthui Kitheka",
# "Dr. Dan Gikonyo",
# "Dr. Betty Gikonyo",
# "Dr. Joseph Lelo",
# "Dr. Eustace Karo",
# "Dr. Anne Gathoni",
# "Dr. Ben Waitara",
# "Dr. Catherine Gichangi",
# "Dr. Kaari Mwirigi",
# "Dr. Robinson Mumenya",
# "Dr. Josiah Gakuru",
# "Dr. Quintus Ekessa",
# "Dr. Muchiri Macharia",
# "Dr. Mberia Gikonyo",
# "Dr. Samuel Gathere",
# "Dr. Anne Beatrice Kihara",
# "Dr. Justus Ngatia",
# "Dr. George Ogweno",
# "Dr. Jackson Mutinda",
# "Dr. Bartilol Kigen",
# "Dr. Anthony K Gikonyo",
# "Dr. Hellen Nguchu",
# "Dr. Danielnduiga",
# "Dr. Samuel Waweru",
# "Dr. Maurice Wambani",
# "Dr. Symon Wairagu",
# "Dr. David Kinyanjui",
# "Dr. Lawrence Gakuu",
# "Dr. Geofrey Karanja Ikundu",
# "Dr. Peter Sandas Nyabutoh",
# "Dr. David Muchiri Munyi",
# "Dr. Joseph Maina",
# "Dr. Samuel Kamami",
# "Dr. Paul Kipngetich Lagat",
# "Dr. Dennis Omari Onyancha",
# "Dr. Oduor G Eric",
# "Dr. Samuel Deya",
# "Dr. Maureen Mwachinga",
# "Dr. Rachael Kangethe",
# "Dr. Amadi, Edgah",
# "Dr. Arunga Kevin",
# "Dr. Boore, John K.",
# "Dr. Gitura, Bernard Muriuki",
# "Dr. Kanja S. Kaguri",
# "Dr. Karanja, Wahome",
# "Dr. Kiboi Julius",
# "Dr. Kiko, Mary M.",
# "Dr. Koech, Kennedy",
# "Dr. Lessan Joel",
# "Dr. Maimba, John M.",
# "Dr. Masinde, Peter",
# "Dr. Michoma Morara Peter",
# "Dr. Michoma, Peter M.",
# "Dr. Mokomba Alfred",
# "Dr. Monda, Simeon M.",
# "Dr. Murage, Wachira",
# "Dr. Mwangi Gicheru",
# "Dr. Mwangi, Njeri Grace",
# "Dr. Nassir, Faiza",
# "Dr. Ngigi John",
# "Dr. Nyamu, Muriithi",
# "Dr. Ochungo Peter",
# "Dr. Odula Paul",
# "Dr. Okech, Violet C A",
# "Dr. Okemwa, Minda",
# "Dr. Ong'ech, John O.",
# "Dr. Onyango, Oscar Muwale",
# "Dr. Waihenya, Charles Githiaka",
# "Dr. Were, Anthony O.",
# "Dr Vitalis Mung'ayi",
# "Dr Dorothy Kamya",
# "Dr Jimmie Kabugi",
# "Dr Linda Thorpe",
# "Dr Preeti Jabbal",
# "Dr Gulnaz Mahmoud",
# "Dr Megan Mahoney",
# "Dr Jacob Shabani",
# "Dr Ravi Sharma",
# "Dr Gerald Yonga",
# "Dr James Jowi",
# "Dr Swati Das",
# "Dr Nancy Kunyiha",
# "Dr Jeilan Mohammed",
# "Dr Asim Shaik ",
# "Dr Alice Musibi",
# "Dr William Macharia",
# "Dr Pauline Samia",
# "Dr John Tole",
# "Dr Rose Kamenwa",
# "Dr Roseline Ochieng",
# "Dr Peter Ojwang",
# "Dr Gunturu Revathi",
# "Dr Sudhir Vinayak",
# "Dr Khalid Makhdomi",
# "Dr Saleem Malik",
# "Dr Joyce Sande",
# "Dr Sheila Waa",
# "Mr. Paresh Devani",
# "Prof. Ilako R. Dunera",
# "Dr. Jin, Mohamedhussain",
# "Dr. Kairu, Stephen Mbugua",
# "Dr. Kamotho, Charles G.",
# "Dr. Sandeep Acharya",
# "Dr. Jandu, Harbaksh",
# "Dr. Daniel Mbinga",
# "Dr. Hemed Twahir",
# "Dr. Tariq Lodhi",
# "Dr. Wangari Siika",
# "Dr. Salim K. Noorani",
# "Dr. Victor Njom",
# "Dr. Firoz Alimohamed",
# "Dr. Rishad Shosi",
# "Dr. Gordon Yossa",
# "Dr. Victor Bandika",
# "Dr. Fathiya El-maawy",
# "Dr Joseph Okanga",
# "Dr Shamina Jivaji",
# "Dr Fredrick Nondi",
# "Dr Mwanaisha Omar Hatimy",
# "Dr Mary Othigo",
# "Dr Mahesh Chudasama",
# "Dr Aruna Chudasama",
# "Dr Yusuf Palkhi",
# "Dr.Sadik",
# "Dr. Raburu O.",
# "Dr. OtienoJames Obondi",
# "Dr. Odondi John",
# "Dr. Onyang F.N",
# "Dr. Chek Philip",
# "Dr. Allibhoy Feroz",
# "Dr. Bonyo Beatrice",
# "Dr. Badia  W. A.",
# "Dr. Kalande Nassa",
# "Dr. Chek Philip Kai",
# "Dr. Odeny David",
# "Dr. Ofafa Adede",
# "Dr. Oduto E.O",
# "Dr. Kumar Nehra Suresh",
# ].each do |company|
  
#  @healthcare = Industry.find_by_title("Healthcare")
#   healthcare_id = @healthcare.id    	
#   Company.create(:title=>company,:industry_id=> healthcare_id)
# end



# puts Maintainence.first_or_create